// components/AdminLayout.js

import { Inter } from "next/font/google";
import Head from "next/head";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

const AdminLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <>
      <Head>
        <title>Appetite Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="min-h-screen bg-gray-100">
        <header className="bg-gray-800 text-white py-4">
          <nav className="container mx-auto">
            <ul className="flex">
              <li className="mr-6">
                <Link href="/admin/dashboard" className="hover:underline">
                  Dashboard
                </Link>
              </li>
              <li className="mr-6">
                <Link href="/admin/posts" className="hover:underline">
                  Menu
                </Link>
              </li>
              {/* Add more navigation links as needed */}
            </ul>
          </nav>
        </header>

        <main className="container mx-auto py-8">{children}</main>

        <footer className="bg-gray-800 text-white py-4 text-center">
          <p>&copy; {new Date().getFullYear()} Appetite Admin</p>
        </footer>
      </div>
    </>
  );
};

export default AdminLayout;
